/*
 Given a list of names, organize a beer exchange such that each
 person is randomly assigned someone else to give a beer to,
 and someone to receive a beer from.
 Caveat: A person cannot receive a beer from the same person to whom they are gifting one.
 */



//Global Scope?
var names = []
var exchangelist = []
var firstname
var firstreceiver

function shuffle(array) {
	/*
	fisher-yates shuffle 
	copy/pasted from 
	http://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array
	*/
    var currentIndex = array.length, temporaryValue, randomIndex;

    // While there remain elements to shuffle...
    while (0 !== currentIndex) {

        // Pick a remaining element...
        randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex -= 1;

        // And swap it with the current element.
        temporaryValue = array[currentIndex];
        array[currentIndex] = array[randomIndex];
        array[randomIndex] = temporaryValue;
    }

    return array;
}
function removeA(arr) {
	/*
	Popular way to remove an item from an array by val.
	Taken from SA here:
	http://stackoverflow.com/questions/3954438/remove-item-from-array-by-value
	*/
    var what, a = arguments, L = a.length, ax;
    while (L > 1 && arr.length) {
        what = a[--L];
        while ((ax= arr.indexOf(what)) !== -1) {
            arr.splice(ax, 1);
        }
    }
    return arr;
}


function random(maxnum) {
	/*
	Simple function to get a random index from
	a list
	*/
	var num = Math.floor((Math.random() * maxnum))
	num = num > 0 ? num -1 : num
	return num
}

function tco(f) {
	/*
	A decorator to trampoline recursive
	functions (replace recursion with a loop).
	Gets around memory usage and browser limitations.
	Solution from here:
	http://www.integralist.co.uk/posts/js-recursion.html
	*/
    var value;
    var active = false;
    var accumulated = [];

    return function accumulator() {
        accumulated.push(arguments);

        if (!active) {
            active = true;

            while (accumulated.length) {
                value = f.apply(this, accumulated.shift());
            }

            active = false;

            return value;
        }
    }
}


var doExchange = tco(function(giver, name, receiver){

   /*
      recursive function to populate exchangelist
   */

	var exchange = [giver, name, receiver]

   removeA(names,giver)

   exchangelist.push(exchange)
   //console.log(exchange)
    
   if(names.length){
      newgiver = names[random(names.length)]
      return doExchange(newgiver, giver, name)
	}
   else {
      exchange = [firstreceiver,giver, name]
      //console.log(exchange)
      exchangelist.push(exchange)

		exchange = [firstname,firstreceiver,giver]
	   //console.log(exchange)
		exchangelist.push(exchange)
		return
   } 
})


function runSwap(){
	/*
	Main function that is called by html (or node)
	*/
	names = ['Tyrion', 'Daenerys', 'Bronn', 'Margaery', 'Brienne']
	//names = ['AARON','ABDUL','ABE','ABEL','ABRAHAM','ABRAM','ADALBERTO','ADAM','ADAN','ADOLFO','ADOLPH','ADRIAN','AGUSTIN','AHMAD','AHMED','AL','ALAN','ALBERT','ALBERTO','ALDEN','ALDO','ALEC','ALEJANDRO','ALEX','ALEXANDER','ALEXIS','ALFONSO','ALFONZO','ALFRED','ALFREDO','ALI','ALLAN','ALLEN','ALONSO','ALONZO','ALPHONSE','ALPHONSO','ALTON','ALVA','ALVARO','ALVIN','AMADO','AMBROSE','AMOS','ANDERSON','ANDRE','ANDREA','ANDREAS','ANDRES','ANDREW','ANDY','ANGEL','ANGELO','ANIBAL','ANTHONY','ANTIONE','ANTOINE','ANTON','ANTONE','ANTONIA','ANTONIO','ANTONY','ANTWAN','ARCHIE','ARDEN','ARIEL','ARLEN','ARLIE','ARMAND','ARMANDO','ARNOLD','ARNOLDO','ARNULFO','ARON','ARRON','ART','ARTHUR','ARTURO','ASA','ASHLEY','AUBREY','AUGUST','AUGUSTINE','AUGUSTUS','AURELIO','AUSTIN','AVERY','BARNEY','BARRETT','BARRY','BART','BARTON','BASIL','BEAU','BEN','BENEDICT','BENITO','BENJAMIN','BENNETT','BENNIE','BENNY','BENTON','BERNARD','BERNARDO','BERNIE','BERRY','BERT','BERTRAM','BILL','BILLIE','BILLY','BLAINE','BLAIR','BLAKE','BO','BOB','BOBBIE','BOBBY','BOOKER','BORIS','BOYCE','BOYD','BRAD','BRADFORD','BRADLEY','BRADLY','BRADY','BRAIN','BRANDEN','BRANDON','BRANT','BRENDAN','BRENDON','BRENT','BRENTON','BRET','BRETT','BRIAN','BRICE','BRITT','BROCK','BRODERICK','BROOKS','BRUCE','BRUNO','BRYAN','BRYANT','BRYCE','BRYON','BUCK','BUD','BUDDY','BUFORD','BURL','BURT','BURTON','BUSTER','BYRON','CALEB','CALVIN','CAMERON','CAREY','CARL','CARLO','CARLOS','CARLTON','CARMELO','CARMEN','CARMINE','CAROL','CARROL','CARROLL','CARSON','CARTER','CARY','CASEY','CECIL','CEDRIC','CEDRICK','CESAR','CHAD','CHADWICK','CHANCE','CHANG','CHARLES','CHARLEY','CHARLIE','CHAS','CHASE','CHAUNCEY','CHESTER','CHET','CHI','CHONG','CHRIS','CHRISTIAN','CHRISTOPER','CHRISTOPHER','CHUCK','CHUNG','CLAIR','CLARENCE','CLARK','CLAUD','CLAUDE','CLAUDIO','CLAY','CLAYTON','CLEMENT','CLEMENTE','CLEO','CLETUS','CLEVELAND','CLIFF','CLIFFORD','CLIFTON','CLINT','CLINTON','CLYDE','CODY','COLBY','COLE','COLEMAN','COLIN','COLLIN','COLTON','COLUMBUS','CONNIE','CONRAD','CORDELL','COREY','CORNELIUS','CORNELL','CORTEZ','CORY','COURTNEY','COY','CRAIG','CRISTOBAL','CRISTOPHER','CRUZ','CURT','CURTIS','CYRIL','CYRUS','DALE','DALLAS','DALTON','DAMIAN','DAMIEN','DAMION','DAMON','DAN','DANA','DANE','DANIAL','DANIEL','DANILO','DANNIE','DANNY','DANTE','DARELL','DAREN','DARIN','DARIO','DARIUS','DARNELL','DARON','DARREL','DARRELL','DARREN','DARRICK','DARRIN','DARRON','DARRYL','DARWIN','DARYL','DAVE','DAVID','DAVIS','DEAN','DEANDRE','DEANGELO','DEE','DEL','DELBERT','DELMAR','DELMER','DEMARCUS','DEMETRIUS','DENIS','DENNIS','DENNY','DENVER','DEON','DEREK','DERICK','DERRICK','DESHAWN','DESMOND','DEVIN','DEVON','DEWAYNE','DEWEY','DEWITT','DEXTER','DICK','DIEGO','DILLON','DINO','DION','DIRK','DOMENIC','DOMINGO','DOMINIC','DOMINICK','DOMINIQUE','DON','DONALD','DONG','DONN','DONNELL','DONNIE','DONNY','DONOVAN','DONTE','DORIAN','DORSEY','DOUG','DOUGLAS','DOUGLASS','DOYLE','DREW','DUANE','DUDLEY','DUNCAN','DUSTIN','DUSTY','DWAIN','DWAYNE','DWIGHT','DYLAN','EARL','EARLE','EARNEST','ED','EDDIE','EDDY','EDGAR','EDGARDO','EDISON','EDMOND','EDMUND','EDMUNDO','EDUARDO','EDWARD','EDWARDO','EDWIN','EFRAIN','EFREN','ELBERT','ELDEN','ELDON','ELDRIDGE','ELI','ELIAS','ELIJAH','ELISEO','ELISHA','ELLIOT','ELLIOTT','ELLIS','ELLSWORTH','ELMER','ELMO','ELOY','ELROY','ELTON','ELVIN','ELVIS','ELWOOD','EMANUEL','EMERSON','EMERY','EMIL','EMILE','EMILIO','EMMANUEL','EMMETT','EMMITT','EMORY','ENOCH','ENRIQUE','ERASMO','ERIC','ERICH','ERICK','ERIK','ERIN','ERNEST','ERNESTO','ERNIE','ERROL','ERVIN','ERWIN','ESTEBAN','ETHAN','EUGENE','EUGENIO','EUSEBIO','EVAN','EVERETT','EVERETTE','EZEKIEL','EZEQUIEL','EZRA','FABIAN','FAUSTINO','FAUSTO','FEDERICO','FELIPE','FELIX','FELTON','FERDINAND','FERMIN','FERNANDO','FIDEL','FILIBERTO','FLETCHER','FLORENCIO','FLORENTINO','FLOYD','FOREST','FORREST','FOSTER','FRANCES','FRANCESCO','FRANCIS','FRANCISCO','FRANK','FRANKIE','FRANKLIN','FRANKLYN','FRED','FREDDIE','FREDDY','FREDERIC','FREDERICK','FREDRIC','FREDRICK','FREEMAN','FRITZ','GABRIEL','GAIL','GALE','GALEN','GARFIELD','GARLAND','GARRET','GARRETT','GARRY','GARTH','GARY','GASTON','GAVIN','GAYLE','GAYLORD','GENARO','GENE','GEOFFREY','GEORGE','GERALD','GERALDO','GERARD','GERARDO','GERMAN','GERRY','GIL','GILBERT','GILBERTO','GINO','GIOVANNI','GIUSEPPE','GLEN','GLENN','GONZALO','GORDON','GRADY','GRAHAM','GRAIG','GRANT','GRANVILLE','GREG','GREGG','GREGORIO','GREGORY','GROVER','GUADALUPE','GUILLERMO','GUS','GUSTAVO','GUY','HAI','HAL','HANK','HANS','HARLAN','HARLAND','HARLEY','HAROLD','HARRIS','HARRISON','HARRY','HARVEY','HASSAN','HAYDEN','HAYWOOD','HEATH','HECTOR','HENRY','HERB','HERBERT','HERIBERTO','HERMAN','HERSCHEL','HERSHEL','HILARIO','HILTON','HIPOLITO','HIRAM','HOBERT','HOLLIS','HOMER','HONG','HORACE','HORACIO','HOSEA','HOUSTON','HOWARD','HOYT','HUBERT','HUEY','HUGH','HUGO','HUMBERTO','HUNG','HUNTER','HYMAN','IAN','IGNACIO','IKE','IRA','IRVIN','IRVING','IRWIN','ISAAC','ISAIAH','ISAIAS','ISIAH','ISIDRO','ISMAEL','ISRAEL','ISREAL','ISSAC','IVAN','IVORY','JACINTO','JACK','JACKIE','JACKSON','JACOB','JACQUES','JAE','JAIME','JAKE','JAMAAL','JAMAL','JAMAR','JAME','JAMEL','JAMES','JAMEY','JAMIE','JAMISON','JAN','JARED','JAROD','JARRED','JARRETT','JARROD','JARVIS','JASON','JASPER','JAVIER','JAY','JAYSON','JC','JEAN','JED','JEFF','JEFFEREY','JEFFERSON','JEFFERY','JEFFREY','JEFFRY','JERALD','JERAMY','JERE','JEREMIAH','JEREMY','JERMAINE','JEROLD','JEROME','JEROMY','JERRELL','JERROD','JERROLD','JERRY','JESS','JESSE','JESSIE','JESUS','JEWEL','JEWELL','JIM','JIMMIE','JIMMY','JOAN','JOAQUIN','JODY','JOE','JOEL','JOESPH','JOEY','JOHN','JOHNATHAN','JOHNATHON','JOHNIE','JOHNNIE','JOHNNY','JOHNSON','JON','JONAH','JONAS','JONATHAN','JONATHON','JORDAN','JORDON','JORGE','JOSE','JOSEF','JOSEPH','JOSH','JOSHUA','JOSIAH','JOSPEH','JOSUE','JUAN','JUDE','JUDSON','JULES','JULIAN','JULIO','JULIUS','JUNIOR','JUSTIN','KAREEM','KARL','KASEY','KEENAN','KEITH','KELLEY','KELLY','KELVIN','KEN','KENDALL','KENDRICK','KENETH','KENNETH','KENNITH','KENNY','KENT','KENTON','KERMIT','KERRY','KEVEN','KEVIN','KIETH','KIM','KING','KIP','KIRBY','KIRK','KOREY','KORY','KRAIG','KRIS','KRISTOFER','KRISTOPHER','KURT','KURTIS','KYLE','LACY','LAMAR','LAMONT','LANCE','LANDON','LANE','LANNY','LARRY','LAUREN','LAURENCE','LAVERN','LAVERNE','LAWERENCE','LAWRENCE','LAZARO','LEANDRO','LEE','LEIF','LEIGH','LELAND','LEMUEL','LEN','LENARD','LENNY','LEO','LEON','LEONARD','LEONARDO','LEONEL','LEOPOLDO','LEROY','LES','LESLEY','LESLIE','LESTER','LEVI','LEWIS','LINCOLN','LINDSAY','LINDSEY','LINO','LINWOOD','LIONEL','LLOYD','LOGAN','LON','LONG','LONNIE','LONNY','LOREN','LORENZO','LOU','LOUIE','LOUIS','LOWELL','LOYD','LUCAS','LUCIANO','LUCIEN','LUCIO','LUCIUS','LUIGI','LUIS','LUKE','LUPE','LUTHER','LYLE','LYMAN','LYNDON','LYNN','LYNWOOD','MAC','MACK','MAJOR','MALCOLM','MALCOM','MALIK','MAN','MANUAL','MANUEL','MARC','MARCEL','MARCELINO','MARCELLUS','MARCELO','MARCO','MARCOS','MARCUS','MARGARITO','MARIA','MARIANO','MARIO','MARION','MARK','MARKUS','MARLIN','MARLON','MARQUIS','MARSHALL','MARTIN','MARTY','MARVIN','MARY','MASON','MATHEW','MATT','MATTHEW','MAURICE','MAURICIO','MAURO','MAX','MAXIMO','MAXWELL','MAYNARD','MCKINLEY','MEL','MELVIN','MERLE','MERLIN','MERRILL','MERVIN','MICAH','MICHAEL','MICHAL','MICHALE','MICHEAL','MICHEL','MICKEY','MIGUEL','MIKE','MIKEL','MILAN','MILES','MILFORD','MILLARD','MILO','MILTON','MINH','MIQUEL','MITCH','MITCHEL','MITCHELL','MODESTO','MOHAMED','MOHAMMAD','MOHAMMED','MOISES','MONROE','MONTE','MONTY','MORGAN','MORRIS','MORTON','MOSE','MOSES','MOSHE','MURRAY','MYLES','MYRON','NAPOLEON','NATHAN','NATHANAEL','NATHANIAL','NATHANIEL','NEAL','NED','NEIL','NELSON','NESTOR','NEVILLE','NEWTON','NICHOLAS','NICK','NICKOLAS','NICKY','NICOLAS','NIGEL','NOAH','NOBLE','NOE','NOEL','NOLAN','NORBERT','NORBERTO','NORMAN','NORMAND','NORRIS','NUMBERS','OCTAVIO','ODELL','ODIS','OLEN','OLIN','OLIVER','OLLIE','OMAR','OMER','OREN','ORLANDO','ORVAL','ORVILLE','OSCAR','OSVALDO','OSWALDO','OTHA','OTIS','OTTO','OWEN','PABLO','PALMER','PARIS','PARKER','PASQUALE','PAT','PATRICIA','PATRICK','PAUL','PEDRO','PERCY','PERRY','PETE','PETER','PHIL','PHILIP','PHILLIP','PIERRE','PORFIRIO','PORTER','PRESTON','PRINCE','QUENTIN','QUINCY','QUINN','QUINTIN','QUINTON','RAFAEL','RALEIGH','RALPH','RAMIRO','RAMON','RANDAL','RANDALL','RANDELL','RANDOLPH','RANDY','RAPHAEL','RASHAD','RAUL','RAY','RAYFORD','RAYMON','RAYMOND','RAYMUNDO','REED','REFUGIO','REGGIE','REGINALD','REID','REINALDO','RENALDO','RENATO','RENE','REUBEN','REX','REY','REYES','REYNALDO','RHETT','RICARDO','RICH','RICHARD','RICHIE','RICK','RICKEY','RICKIE','RICKY','RICO','RIGOBERTO','RILEY','ROB','ROBBIE','ROBBY','ROBERT','ROBERTO','ROBIN','ROBT','ROCCO','ROCKY','ROD','RODERICK','RODGER','RODNEY','RODOLFO','RODRICK','RODRIGO','ROGELIO','ROGER','ROLAND','ROLANDO','ROLF','ROLLAND','ROMAN','ROMEO','RON','RONALD','RONNIE','RONNY','ROOSEVELT','RORY','ROSARIO','ROSCOE','ROSENDO','ROSS','ROY','ROYAL','ROYCE','RUBEN','RUBIN','RUDOLF','RUDOLPH','RUDY','RUEBEN','RUFUS','RUPERT','RUSS','RUSSEL','RUSSELL','RUSTY','RYAN','SAL','SALVADOR','SALVATORE','SAM','SAMMIE','SAMMY','SAMUAL','SAMUEL','SANDY','SANFORD','SANG','SANTIAGO','SANTO','SANTOS','SAUL','SCOT','SCOTT','SCOTTIE','SCOTTY','SEAN','SEBASTIAN','SERGIO','SETH','SEYMOUR','SHAD','SHANE','SHANNON','SHAUN','SHAWN','SHAYNE','SHELBY','SHELDON','SHELTON','SHERMAN','SHERWOOD','SHIRLEY','SHON','SID','SIDNEY','SILAS','SIMON','SOL','SOLOMON','SON','SONNY','SPENCER','STACEY','STACY','STAN','STANFORD','STANLEY','STANTON','STEFAN','STEPHAN','STEPHEN','STERLING','STEVE','STEVEN','STEVIE','STEWART','STUART','SUNG','SYDNEY',
	//'AARONzz','ABDULzz','ABEzz','ABELzz','ABRAHAMzz','ABRAMzz','ADALBERTOzz','ADAMzz','ADANzz','ADOLFOzz','ADOLPHzz','ADRIANzz','AGUSTINzz','AHMADzz','AHMEDzz','ALzz','ALANzz','ALBERTzz','ALBERTOzz','ALDENzz','ALDOzz','ALECzz','ALEJANDROzz','ALEXzz','ALEXANDERzz','ALEXISzz','ALFONSOzz','ALFONZOzz','ALFREDzz','ALFREDOzz','ALIzz','ALLANzz','ALLENzz','ALONSOzz','ALONZOzz','ALPHONSEzz','ALPHONSOzz','ALTONzz','ALVAzz','ALVAROzz','ALVINzz','AMADOzz','AMBROSEzz','AMOSzz','ANDERSONzz','ANDREzz','ANDREAzz','ANDREASzz','ANDRESzz','ANDREWzz','ANDYzz','ANGELzz','ANGELOzz','ANIBALzz','ANTHONYzz','ANTIONEzz','ANTOINEzz','ANTONzz','ANTONEzz','ANTONIAzz','ANTONIOzz','ANTONYzz','ANTWANzz','ARCHIEzz','ARDENzz','ARIELzz','ARLENzz','ARLIEzz','ARMANDzz','ARMANDOzz','ARNOLDzz','ARNOLDOzz','ARNULFOzz','ARONzz','ARRONzz','ARTzz','ARTHURzz','ARTUROzz','ASAzz','ASHLEYzz','AUBREYzz','AUGUSTzz','AUGUSTINEzz','AUGUSTUSzz','AURELIOzz','AUSTINzz','AVERYzz','BARNEYzz','BARRETTzz','BARRYzz','BARTzz','BARTONzz','BASILzz','BEAUzz','BENzz','BENEDICTzz','BENITOzz','BENJAMINzz','BENNETTzz','BENNIEzz','BENNYzz','BENTONzz','BERNARDzz','BERNARDOzz','BERNIEzz','BERRYzz','BERTzz','BERTRAMzz','BILLzz','BILLIEzz','BILLYzz','BLAINEzz','BLAIRzz','BLAKEzz','BOzz','BOBzz','BOBBIEzz','BOBBYzz','BOOKERzz','BORISzz','BOYCEzz','BOYDzz','BRADzz','BRADFORDzz','BRADLEYzz','BRADLYzz','BRADYzz','BRAINzz','BRANDENzz','BRANDONzz','BRANTzz','BRENDANzz','BRENDONzz','BRENTzz','BRENTONzz','BRETzz','BRETTzz','BRIANzz','BRICEzz','BRITTzz','BROCKzz','BRODERICKzz','BROOKSzz','BRUCEzz','BRUNOzz','BRYANzz','BRYANTzz','BRYCEzz','BRYONzz','BUCKzz','BUDzz','BUDDYzz','BUFORDzz','BURLzz','BURTzz','BURTONzz','BUSTERzz','BYRONzz','CALEBzz','CALVINzz','CAMERONzz','CAREYzz','CARLzz','CARLOzz','CARLOSzz','CARLTONzz','CARMELOzz','CARMENzz','CARMINEzz','CAROLzz','CARROLzz','CARROLLzz','CARSONzz','CARTERzz','CARYzz','CASEYzz','CECILzz','CEDRICzz','CEDRICKzz','CESARzz','CHADzz','CHADWICKzz','CHANCEzz','CHANGzz','CHARLESzz','CHARLEYzz','CHARLIEzz','CHASzz','CHASEzz','CHAUNCEYzz','CHESTERzz','CHETzz','CHIzz','CHONGzz','CHRISzz','CHRISTIANzz','CHRISTOPERzz','CHRISTOPHERzz','CHUCKzz','CHUNGzz','CLAIRzz','CLARENCEzz','CLARKzz','CLAUDzz','CLAUDEzz','CLAUDIOzz','CLAYzz','CLAYTONzz','CLEMENTzz','CLEMENTEzz','CLEOzz','CLETUSzz','CLEVELANDzz','CLIFFzz','CLIFFORDzz','CLIFTONzz','CLINTzz','CLINTONzz','CLYDEzz','CODYzz','COLBYzz','COLEzz','COLEMANzz','COLINzz','COLLINzz','COLTONzz','COLUMBUSzz','CONNIEzz','CONRADzz','CORDELLzz','COREYzz','CORNELIUSzz','CORNELLzz','CORTEZzz','CORYzz','COURTNEYzz','COYzz','CRAIGzz','CRISTOBALzz','CRISTOPHERzz','CRUZzz','CURTzz','CURTISzz','CYRILzz','CYRUSzz','DALEzz','DALLASzz','DALTONzz','DAMIANzz','DAMIENzz','DAMIONzz','DAMONzz','DANzz','DANAzz','DANEzz','DANIALzz','DANIELzz','DANILOzz','DANNIEzz','DANNYzz','DANTEzz','DARELLzz','DARENzz','DARINzz','DARIOzz','DARIUSzz','DARNELLzz','DARONzz','DARRELzz','DARRELLzz','DARRENzz','DARRICKzz','DARRINzz','DARRONzz','DARRYLzz','DARWINzz','DARYLzz','DAVEzz','DAVIDzz','DAVISzz','DEANzz','DEANDREzz','DEANGELOzz','DEEzz','DELzz','DELBERTzz','DELMARzz','DELMERzz','DEMARCUSzz','DEMETRIUSzz','DENISzz','DENNISzz','DENNYzz','DENVERzz','DEONzz','DEREKzz','DERICKzz','DERRICKzz','DESHAWNzz','DESMONDzz','DEVINzz','DEVONzz','DEWAYNEzz','DEWEYzz','DEWITTzz','DEXTERzz','DICKzz','DIEGOzz','DILLONzz','DINOzz','DIONzz','DIRKzz','DOMENICzz','DOMINGOzz','DOMINICzz','DOMINICKzz','DOMINIQUEzz','DONzz','DONALDzz','DONGzz','DONNzz','DONNELLzz','DONNIEzz','DONNYzz','DONOVANzz','DONTEzz','DORIANzz','DORSEYzz','DOUGzz','DOUGLASzz','DOUGLASSzz','DOYLEzz','DREWzz','DUANEzz','DUDLEYzz','DUNCANzz','DUSTINzz','DUSTYzz','DWAINzz','DWAYNEzz','DWIGHTzz','DYLANzz','EARLzz','EARLEzz','EARNESTzz','EDzz','EDDIEzz','EDDYzz','EDGARzz','EDGARDOzz','EDISONzz','EDMONDzz','EDMUNDzz','EDMUNDOzz','EDUARDOzz','EDWARDzz','EDWARDOzz','EDWINzz','EFRAINzz','EFRENzz','ELBERTzz','ELDENzz','ELDONzz','ELDRIDGEzz','ELIzz','ELIASzz','ELIJAHzz','ELISEOzz','ELISHAzz','ELLIOTzz','ELLIOTTzz','ELLISzz','ELLSWORTHzz','ELMERzz','ELMOzz','ELOYzz','ELROYzz','ELTONzz','ELVINzz','ELVISzz','ELWOODzz','EMANUELzz','EMERSONzz','EMERYzz','EMILzz','EMILEzz','EMILIOzz','EMMANUELzz','EMMETTzz','EMMITTzz','EMORYzz','ENOCHzz','ENRIQUEzz','ERASMOzz','ERICzz','ERICHzz','ERICKzz','ERIKzz','ERINzz','ERNESTzz','ERNESTOzz','ERNIEzz','ERROLzz','ERVINzz','ERWINzz','ESTEBANzz','ETHANzz','EUGENEzz','EUGENIOzz','EUSEBIOzz','EVANzz','EVERETTzz','EVERETTEzz','EZEKIELzz','EZEQUIELzz','EZRAzz','FABIANzz','FAUSTINOzz','FAUSTOzz','FEDERICOzz','FELIPEzz','FELIXzz','FELTONzz','FERDINANDzz','FERMINzz','FERNANDOzz','FIDELzz','FILIBERTOzz','FLETCHERzz','FLORENCIOzz','FLORENTINOzz','FLOYDzz','FORESTzz','FORRESTzz','FOSTERzz','FRANCESzz','FRANCESCOzz','FRANCISzz','FRANCISCOzz','FRANKzz','FRANKIEzz','FRANKLINzz','FRANKLYNzz','FREDzz','FREDDIEzz','FREDDYzz','FREDERICzz','FREDERICKzz','FREDRICzz','FREDRICKzz','FREEMANzz','FRITZzz','GABRIELzz','GAILzz','GALEzz','GALENzz','GARFIELDzz','GARLANDzz','GARRETzz','GARRETTzz','GARRYzz','GARTHzz','GARYzz','GASTONzz','GAVINzz','GAYLEzz','GAYLORDzz','GENAROzz','GENEzz','GEOFFREYzz','GEORGEzz','GERALDzz','GERALDOzz','GERARDzz','GERARDOzz','GERMANzz','GERRYzz','GILzz','GILBERTzz','GILBERTOzz','GINOzz','GIOVANNIzz','GIUSEPPEzz','GLENzz','GLENNzz','GONZALOzz','GORDONzz','GRADYzz','GRAHAMzz','GRAIGzz','GRANTzz','GRANVILLEzz','GREGzz','GREGGzz','GREGORIOzz','GREGORYzz','GROVERzz','GUADALUPEzz','GUILLERMOzz','GUSzz','GUSTAVOzz','GUYzz','HAIzz','HALzz','HANKzz','HANSzz','HARLANzz','HARLANDzz','HARLEYzz','HAROLDzz','HARRISzz','HARRISONzz','HARRYzz','HARVEYzz','HASSANzz','HAYDENzz','HAYWOODzz','HEATHzz','HECTORzz','HENRYzz','HERBzz','HERBERTzz','HERIBERTOzz','HERMANzz','HERSCHELzz','HERSHELzz','HILARIOzz','HILTONzz','HIPOLITOzz','HIRAMzz','HOBERTzz','HOLLISzz','HOMERzz','HONGzz','HORACEzz','HORACIOzz','HOSEAzz','HOUSTONzz','HOWARDzz','HOYTzz','HUBERTzz','HUEYzz','HUGHzz','HUGOzz','HUMBERTOzz','HUNGzz','HUNTERzz','HYMANzz','IANzz','IGNACIOzz','IKEzz','IRAzz','IRVINzz','IRVINGzz','IRWINzz','ISAACzz','ISAIAHzz','ISAIASzz','ISIAHzz','ISIDROzz','ISMAELzz','ISRAELzz','ISREALzz','ISSACzz','IVANzz','IVORYzz','JACINTOzz','JACKzz','JACKIEzz','JACKSONzz','JACOBzz','JACQUESzz','JAEzz','JAIMEzz','JAKEzz','JAMAALzz','JAMALzz','JAMARzz','JAMEzz','JAMELzz','JAMESzz','JAMEYzz','JAMIEzz','JAMISONzz','JANzz','JAREDzz','JARODzz','JARREDzz','JARRETTzz','JARRODzz','JARVISzz','JASONzz','JASPERzz','JAVIERzz','JAYzz','JAYSONzz','JCzz','JEANzz','JEDzz','JEFFzz','JEFFEREYzz','JEFFERSONzz','JEFFERYzz','JEFFREYzz','JEFFRYzz','JERALDzz','JERAMYzz','JEREzz','JEREMIAHzz','JEREMYzz','JERMAINEzz','JEROLDzz','JEROMEzz','JEROMYzz','JERRELLzz','JERRODzz','JERROLDzz','JERRYzz','JESSzz','JESSEzz','JESSIEzz','JESUSzz','JEWELzz','JEWELLzz','JIMzz','JIMMIEzz','JIMMYzz','JOANzz','JOAQUINzz','JODYzz','JOEzz','JOELzz','JOESPHzz','JOEYzz','JOHNzz','JOHNATHANzz','JOHNATHONzz','JOHNIEzz','JOHNNIEzz','JOHNNYzz','JOHNSONzz','JONzz','JONAHzz','JONASzz','JONATHANzz','JONATHONzz','JORDANzz','JORDONzz','JORGEzz','JOSEzz','JOSEFzz','JOSEPHzz','JOSHzz','JOSHUAzz','JOSIAHzz','JOSPEHzz','JOSUEzz','JUANzz','JUDEzz','JUDSONzz','JULESzz','JULIANzz','JULIOzz','JULIUSzz','JUNIORzz','JUSTINzz','KAREEMzz','KARLzz','KASEYzz','KEENANzz','KEITHzz','KELLEYzz','KELLYzz','KELVINzz','KENzz','KENDALLzz','KENDRICKzz','KENETHzz','KENNETHzz','KENNITHzz','KENNYzz','KENTzz','KENTONzz','KERMITzz','KERRYzz','KEVENzz','KEVINzz','KIETHzz','KIMzz','KINGzz','KIPzz','KIRBYzz','KIRKzz','KOREYzz','KORYzz','KRAIGzz','KRISzz','KRISTOFERzz','KRISTOPHERzz','KURTzz','KURTISzz','KYLEzz','LACYzz','LAMARzz','LAMONTzz','LANCEzz','LANDONzz','LANEzz','LANNYzz','LARRYzz','LAURENzz','LAURENCEzz','LAVERNzz','LAVERNEzz','LAWERENCEzz','LAWRENCEzz','LAZAROzz','LEANDROzz','LEEzz','LEIFzz','LEIGHzz','LELANDzz','LEMUELzz','LENzz','LENARDzz','LENNYzz','LEOzz','LEONzz','LEONARDzz','LEONARDOzz','LEONELzz','LEOPOLDOzz','LEROYzz','LESzz','LESLEYzz','LESLIEzz','LESTERzz','LEVIzz','LEWISzz','LINCOLNzz','LINDSAYzz','LINDSEYzz','LINOzz','LINWOODzz','LIONELzz','LLOYDzz','LOGANzz','LONzz','LONGzz','LONNIEzz','LONNYzz','LORENzz','LORENZOzz','LOUzz','LOUIEzz','LOUISzz','LOWELLzz','LOYDzz','LUCASzz','LUCIANOzz','LUCIENzz','LUCIOzz','LUCIUSzz','LUIGIzz','LUISzz','LUKEzz','LUPEzz','LUTHERzz','LYLEzz','LYMANzz','LYNDONzz','LYNNzz','LYNWOODzz','MACzz','MACKzz','MAJORzz','MALCOLMzz','MALCOMzz','MALIKzz','MANzz','MANUALzz','MANUELzz','MARCzz','MARCELzz','MARCELINOzz','MARCELLUSzz','MARCELOzz','MARCOzz','MARCOSzz','MARCUSzz','MARGARITOzz','MARIAzz','MARIANOzz','MARIOzz','MARIONzz','MARKzz','MARKUSzz','MARLINzz','MARLONzz','MARQUISzz','MARSHALLzz','MARTINzz','MARTYzz','MARVINzz','MARYzz','MASONzz','MATHEWzz','MATTzz','MATTHEWzz','MAURICEzz','MAURICIOzz','MAUROzz','MAXzz','MAXIMOzz','MAXWELLzz','MAYNARDzz','MCKINLEYzz','MELzz','MELVINzz','MERLEzz','MERLINzz','MERRILLzz','MERVINzz','MICAHzz','MICHAELzz','MICHALzz','MICHALEzz','MICHEALzz','MICHELzz','MICKEYzz','MIGUELzz','MIKEzz','MIKELzz','MILANzz','MILESzz','MILFORDzz','MILLARDzz','MILOzz','MILTONzz','MINHzz','MIQUELzz','MITCHzz','MITCHELzz','MITCHELLzz','MODESTOzz','MOHAMEDzz','MOHAMMADzz','MOHAMMEDzz','MOISESzz','MONROEzz','MONTEzz','MONTYzz','MORGANzz','MORRISzz','MORTONzz','MOSEzz','MOSESzz','MOSHEzz','MURRAYzz','MYLESzz','MYRONzz','NAPOLEONzz','NATHANzz','NATHANAELzz','NATHANIALzz','NATHANIELzz','NEALzz','NEDzz','NEILzz','NELSONzz','NESTORzz','NEVILLEzz','NEWTONzz','NICHOLASzz','NICKzz','NICKOLASzz','NICKYzz','NICOLASzz','NIGELzz','NOAHzz','NOBLEzz','NOEzz','NOELzz','NOLANzz','NORBERTzz','NORBERTOzz','NORMANzz','NORMANDzz','NORRISzz','NUMBERSzz','OCTAVIOzz','ODELLzz','ODISzz','OLENzz','OLINzz','OLIVERzz','OLLIEzz','OMARzz','OMERzz','ORENzz','ORLANDOzz','ORVALzz','ORVILLEzz','OSCARzz','OSVALDOzz','OSWALDOzz','OTHAzz','OTISzz','OTTOzz','OWENzz','PABLOzz','PALMERzz','PARISzz','PARKERzz','PASQUALEzz','PATzz','PATRICIAzz','PATRICKzz','PAULzz','PEDROzz','PERCYzz','PERRYzz','PETEzz','PETERzz','PHILzz','PHILIPzz','PHILLIPzz','PIERREzz','PORFIRIOzz','PORTERzz','PRESTONzz','PRINCEzz','QUENTINzz','QUINCYzz','QUINNzz','QUINTINzz','QUINTONzz','RAFAELzz','RALEIGHzz','RALPHzz','RAMIROzz','RAMONzz','RANDALzz','RANDALLzz','RANDELLzz','RANDOLPHzz','RANDYzz','RAPHAELzz','RASHADzz','RAULzz','RAYzz','RAYFORDzz','RAYMONzz','RAYMONDzz','RAYMUNDOzz','REEDzz','REFUGIOzz','REGGIEzz','REGINALDzz','REIDzz','REINALDOzz','RENALDOzz','RENATOzz','RENEzz','REUBENzz','REXzz','REYzz','REYESzz','REYNALDOzz','RHETTzz','RICARDOzz','RICHzz','RICHARDzz','RICHIEzz','RICKzz','RICKEYzz','RICKIEzz','RICKYzz','RICOzz','RIGOBERTOzz','RILEYzz','ROBzz','ROBBIEzz','ROBBYzz','ROBERTzz','ROBERTOzz','ROBINzz','ROBTzz','ROCCOzz','ROCKYzz','RODzz','RODERICKzz','RODGERzz','RODNEYzz','RODOLFOzz','RODRICKzz','RODRIGOzz','ROGELIOzz','ROGERzz','ROLANDzz','ROLANDOzz','ROLFzz','ROLLANDzz','ROMANzz','ROMEOzz','RONzz','RONALDzz','RONNIEzz','RONNYzz','ROOSEVELTzz','RORYzz','ROSARIOzz','ROSCOEzz','ROSENDOzz','ROSSzz','ROYzz','ROYALzz','ROYCEzz','RUBENzz','RUBINzz','RUDOLFzz','RUDOLPHzz','RUDYzz','RUEBENzz','RUFUSzz','RUPERTzz','RUSSzz','RUSSELzz','RUSSELLzz','RUSTYzz','RYANzz','SALzz','SALVADORzz','SALVATOREzz','SAMzz','SAMMIEzz','SAMMYzz','SAMUALzz','SAMUELzz','SANDYzz','SANFORDzz','SANGzz','SANTIAGOzz','SANTOzz','SANTOSzz','SAULzz','SCOTzz','SCOTTzz','SCOTTIEzz','SCOTTYzz','SEANzz','SEBASTIANzz','SERGIOzz','SETHzz','SEYMOURzz','SHADzz','SHANEzz','SHANNONzz','SHAUNzz','SHAWNzz','SHAYNEzz','SHELBYzz','SHELDONzz','SHELTONzz','SHERMANzz','SHERWOODzz','SHIRLEYzz','SHONzz','SIDzz','SIDNEYzz','SILASzz','SIMONzz','SOLzz','SOLOMONzz','SONzz','SONNYzz','SPENCERzz','STACEYzz','STACYzz','STANzz','STANFORDzz','STANLEYzz','STANTONzz','STEFANzz','STEPHANzz','STEPHENzz','STERLINGzz','STEVEzz','STEVENzz','STEVIEzz','STEWARTzz','STUARTzz','SUNGzz','SYDNEYzz','SYLVESTERzz','TADzz','TANNERzz','TAYLORzz','TEDzz','TEDDYzz','TEODOROzz','TERENCEzz','TERRANCEzz','TERRELLzz','TERRENCEzz','TERRYzz','THADzz','THADDEUSzz','THANHzz','THEOzz','THEODOREzz','THERONzz','THOMASzz','THURMANzz','TIMzz','TIMMYzz','TIMOTHYzz','TITUSzz','TOBIASzz','TOBYzz','TODzz','TODDzz','TOMzz','TOMASzz','TOMMIEzz','TOMMYzz','TONEYzz','TONYzz','TORYzz','TRACEYzz','TRACYzz','TRAVISzz','TRENTzz','TRENTONzz','TREVORzz','TREYzz','TRINIDADzz','TRISTANzz','TROYzz','TRUMANzz','TUANzz','TYzz','TYLERzz','TYREEzz','TYRELLzz','TYRONzz','TYRONEzz','TYSONzz','ULYSSESzz','VALzz','VALENTINzz','VALENTINEzz','VANzz','VANCEzz','VAUGHNzz','VERNzz','VERNONzz','VICENTEzz','VICTORzz','VINCEzz','VINCENTzz','VINCENZOzz','VIRGILzz','VIRGILIOzz','VITOzz','VONzz','WADEzz','WALDOzz','WALKERzz','WALLACEzz','WALLYzz','WALTERzz','WALTONzz','WARDzz','WARNERzz','WARRENzz','WAYLONzz','WAYNEzz','WELDONzz','WENDELLzz','WERNERzz','WESzz','WESLEYzz','WESTONzz','WHITNEYzz','WILBERzz','WILBERTzz','WILBURzz','WILBURNzz','WILEYzz','WILFORDzz','WILFREDzz','WILFREDOzz','WILLzz','WILLARDzz','WILLIAMzz','WILLIAMSzz','WILLIANzz','WILLIEzz','WILLISzz','WILLYzz','WILMERzz','WILSONzz','WILTONzz','WINFORDzz','WINFREDzz','WINSTONzz','WMzz','WOODROWzz','WYATTzz','XAVIERzz','YONGzz','YOUNGzz','ZACHARIAHzz','ZACHARYzz','ZACHERYzz','ZACKzz','ZACKARYzz','ZANEzz']
	names = shuffle(names)
	
	exchangelist = []
	var giver = names[0]
	firstname = names[1]
	removeA(names,firstname)
	firstreceiver = names[2]
	removeA(names,firstreceiver)

	doExchange(giver, firstname, firstreceiver)

	exchangelist.forEach(function(exchange) {
		console.log(exchange[1] + " gives to " + exchange[2]) //need to open dev tools to see result
	})
}

exports = runSwap() //for running in node